openapi: 3.0.3
info:
  title: Calendar API
  version: v5
servers:
  - url: /
paths:
  /hello:
    get:
      description: Request the server to greet you
      operationId: getHelloWorld
      parameters:
        - $ref: "#/components/parameters/x-okapi-tenant"
        - name: salutation
          in: query
          schema:
            type: string
            default: "Welcome"
          description: The requested salutation
          required: false
      responses:
        "200":
          description: A hello-related message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/greeting"
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
components:
  schemas:
    greeting:
      $ref: schemas/greeting.json
  parameters:
    x-okapi-tenant:
      name: x-okapi-tenant
      in: header
      description: X-Okapi-Tenant Value
      required: true
      schema:
        type: string
